sudo: required
services:
  - docker
env:
  global:
    - CENTOS_VERSION=7
    - UBUNTU_VERSION=18
matrix:
  include:
  - env: CENTOS=true
  - env: UBUNTU=true
before_install:
  - chmod +x *.sh
script:
  - echo "Build local image"
  - if [[ "$CENTOS" == "true" ]]; then ./build-centos.sh ; fi
  - if [[ "$UBUNTU" == "true" ]]; then ./build-ubuntu.sh ; fi
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master