sudo: required
services:
  - docker
env:
  global:
    - CENTOS_VERSION=7
    - UBUNTU_VERSION=18
env:
  - DOCKER_OS="CENTOS"
  - DOCKER_OS="UBUNTU"
before_install:
  - chmod +x *.sh
script:
  - echo "Build local image"
  - if [[ "$DOCKER_OS=="CENTOS" ]]; then ./build-centos.sh ; fi
  - if [[ "$DOCKER_OS=="UBUNTU" ]]; then ./build-ubuntu.sh ; fi
jobs:
  include:
    - stage: deploy
      env: DOCKER_OS=none
      install: skip # bundle install is not required
      script: bash ./docker_push.sh